### Buscando todos os produtos
GET http://localhost:3000/produtos
Content-Type: application/json

### Inserindo um produto
POST http://localhost:3000/produto
Content-Type: application/json

{
    "nome": "Z Fold 7",
    "preco": 5200.90
}